/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdaptiveCol: typeof import('./layouts/AdaptiveCol.vue')['default']
    AdaptiveContainer: typeof import('./layouts/AdaptiveContainer.vue')['default']
    AdaptiveContainerRow: typeof import('./components/AdaptiveContainerRow.vue')['default']
    AdaptiveRightSidebar: typeof import('./layouts/AdaptiveRightSidebarLayout.vue')['default']
    AdaptiveRow: typeof import('./layouts/AdaptiveRow.vue')['default']
    AdaptiveSidebar: typeof import('./layouts/AdaptiveSidebar.vue')['default']
    AuthorList: typeof import('./components/AuthorList.vue')['default']
    AuthorListItem: typeof import('./components/AuthorListItem.vue')['default']
    AuthorPageHeader: typeof import('./components/AuthorPageHeader.vue')['default']
    BookCard: typeof import('./components/BookCard.vue')['default']
    BookGrid: typeof import('./components/BookGrid.vue')['default']
    BookImagesCarousel: typeof import('./components/BookImagesCarousel.vue')['default']
    BookInfoCharacteristics: typeof import('./components/BookInfoCharacteristics.vue')['default']
    BookInfoComments: typeof import('./components/BookInfoComments.vue')['default']
    BookInfoCommentsCreate: typeof import('./components/BookInfoCommentsCreate.vue')['default']
    BookInfoHead: typeof import('./components/BookInfoHead.vue')['default']
    BookInfoHeadImages: typeof import('./components/BookInfoHeadImages.vue')['default']
    BookInfoRatings: typeof import('./components/BookInfoRatings.vue')['default']
    BookInfoSidebar: typeof import('./components/BookInfoSidebar.vue')['default']
    BookList: typeof import('./components/BookList.vue')['default']
    BookListItem: typeof import('./components/BookListItem.vue')['default']
    BookSectionTabs: typeof import('./components/BookSectionTabs.vue')['default']
    BookView: typeof import('./components/BookView.vue')['default']
    CommentPromotion: typeof import('./components/CommentPromotion.vue')['default']
    CreateAuthorImage: typeof import('./components/CreateAuthorImage.vue')['default']
    CreateBookCharacteristics: typeof import('./components/CreateBookCharacteristics.vue')['default']
    CreateBookImages: typeof import('./components/CreateBookImages.vue')['default']
    CreateBookImagesCarousel: typeof import('./components/CreateBookImagesCarousel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MyAppBar: typeof import('./components/MyAppBar.vue')['default']
    MyInput: typeof import('./components/UI/MyInput.vue')['default']
    MySheet: typeof import('./components/MySheet.vue')['default']
    NavDrawer: typeof import('./components/NavDrawer.vue')['default']
    PublisherList: typeof import('./components/PublisherList.vue')['default']
    PublisherListItem: typeof import('./components/PublisherListItem.vue')['default']
    PublisherPageHeader: typeof import('./components/PublisherPageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBookFilter: typeof import('./components/SearchBookFilter.vue')['default']
    SearchBookFilterDrawer: typeof import('./components/SearchBookFilterDrawer.vue')['default']
    SearchDialog: typeof import('./components/SearchDialog.vue')['default']
    SearchDialogInput: typeof import('./components/UI/SearchDialogInput.vue')['default']
    SortBySelect: typeof import('./components/UI/SortBySelect.vue')['default']
    UserDataForm: typeof import('./components/UserDataForm.vue')['default']
    UserPageHeader: typeof import('./components/UserPageHeader.vue')['default']
    ViewToggle: typeof import('./components/UI/ViewToggle.vue')['default']
  }
}
