/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AuthorEdit': RouteRecordInfo<'/AuthorEdit', '/AuthorEdit', Record<never, never>, Record<never, never>>,
    '/AuthorPage': RouteRecordInfo<'/AuthorPage', '/AuthorPage', Record<never, never>, Record<never, never>>,
    '/AuthPage': RouteRecordInfo<'/AuthPage', '/AuthPage', Record<never, never>, Record<never, never>>,
    '/BookEdit': RouteRecordInfo<'/BookEdit', '/BookEdit', Record<never, never>, Record<never, never>>,
    '/BookInfo': RouteRecordInfo<'/BookInfo', '/BookInfo', Record<never, never>, Record<never, never>>,
    '/CartPage': RouteRecordInfo<'/CartPage', '/CartPage', Record<never, never>, Record<never, never>>,
    '/CreateAuthor': RouteRecordInfo<'/CreateAuthor', '/CreateAuthor', Record<never, never>, Record<never, never>>,
    '/CreateBook': RouteRecordInfo<'/CreateBook', '/CreateBook', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/LikedBooks': RouteRecordInfo<'/LikedBooks', '/LikedBooks', Record<never, never>, Record<never, never>>,
    '/LoginPage': RouteRecordInfo<'/LoginPage', '/LoginPage', Record<never, never>, Record<never, never>>,
    '/NotFoundPage': RouteRecordInfo<'/NotFoundPage', '/NotFoundPage', Record<never, never>, Record<never, never>>,
    '/PublisherPage': RouteRecordInfo<'/PublisherPage', '/PublisherPage', Record<never, never>, Record<never, never>>,
    '/SearchBook': RouteRecordInfo<'/SearchBook', '/SearchBook', Record<never, never>, Record<never, never>>,
    '/UserPage': RouteRecordInfo<'/UserPage', '/UserPage', Record<never, never>, Record<never, never>>,
  }
}
